#!/bin/bash

# This always run local to the Dockerfile folder.
set -e -o pipefail

for build in $BUILDS; do
  os=$(echo $build | cut -d: -f1)
  name=$(echo $build | cut -d: -f2)
  echo "Building Image ${IMAGE_NAME}_${os}_${name}"
  docker build --build-arg "ARCH=${name}" --tag "${IMAGE_NAME}_${os}_${name}" --file Dockerfile ../..
done
