{{- if and .Values.dashboards.grafana.create (not .Values.dashboards.grafana.secret.existingSecretName)}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unpoller.grafana-secret" . }}
  labels:
    {{- include "unpoller.labels" . | nindent 4 }}
stringData:
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.dashboards.grafana.secret.password  }}
  GF_SECURITY_ADMIN_USER: {{ .Values.dashboards.grafana.secret.username  }}
{{- end }}