{
 "title": "UniFi UAP Insights",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "dataSource", "query": "influxdb" },
   {
    "name": "host",
    "label": "UniFi AP:",
    "query": "show tag values from \"uap\" with key=\"name\""
   }
  ]
 },
 "panels": [
  {
   "title": "AP Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "model" ], "type": "tag" },
      { "params": [ "cfgversion" ], "type": "tag" },
      { "params": [ "board_rev" ], "type": "tag" },
      { "params": [ "serial" ], "type": "tag" },
      { "params": [ "site_id" ], "type": "tag" },
      { "params": [ "bandsteering_mode" ], "type": "tag" },
      { "params": [ "device_ap" ], "type": "tag" }
     ],
     "measurement": "uap",
     "select": [
      [
       { "params": [ "version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Version" ], "type": "alias" }
      ],
      [
       { "params": [ "ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "IP" ], "type": "alias" }
      ],
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "last_seen" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" },
       { "params": [ "Last Seen" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CPU" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "content": "<br>\n<center><b><font size=\"6px\">Unifi UAP</font></b></center>\n"
  },
  { "title": "Now", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 } },
  {
   "title": "5GHz Radio Channel",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "query": "SELECT \"channel\" FROM \"uap_radios\" WHERE (\"device_name\" =~ /^$host$/ AND \"radio\" = 'na') AND $timeFilter GROUP BY \"device_name\"",
     "select": [
      [
       { "params": [ "channel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" }
     ]
    }
   ]
  },
  {
   "title": "5Ghz Radio Tx Power",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "tx_power" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "uap",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "uap",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "2.4GHz Radio Tx Power",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "tx_power" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "radio", "operator": "=", "value": "ng" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "2.4GHz Radio Channel",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "channel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" }
     ]
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "uap",
     "select": [
      [
       { "params": [ "loadavg_1" ], "type": "field" },
       { "params": [ "load 1" ], "type": "alias" }
      ],
      [
       { "params": [ "loadavg_5" ], "type": "field" },
       { "params": [ "laid 5" ], "type": "alias" }
      ],
      [
       { "params": [ "loadavg_15" ], "type": "field" },
       { "params": [ "load15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "uap",
     "select": [
      [
       { "params": [ "mem_buffer" ], "type": "field" },
       { "params": [ "Buffer" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_used" ], "type": "field" },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_total" ], "type": "field" },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Connection Quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "ccq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name 5GHz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" }
     ]
    },
    {
     "alias": "$tag_device_name 2.4GHz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" }
     ]
    }
   ]
  },
  {
   "title": "5 GHz Channel Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "cu_self_rx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "cu_self_tx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "cu_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" }
     ]
    }
   ]
  },
  {
   "title": "2.4GHz Channel Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "cu_self_rx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "cu_self_tx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "cu_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" }
     ]
    }
   ]
  },
  {
   "title": "5 GHz Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name:$col",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" }
     ]
    }
   ]
  },
  {
   "title": "2.4GHz Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name:$col",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" }
     ]
    }
   ]
  },
  {
   "title": "5 GHz Packets",
   "type": "graph",
   "description": "PPS on the na band calculated in 30 second buckets.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name:$col",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" }
     ]
    }
   ]
  },
  {
   "title": "2.4GHz Packets",
   "type": "graph",
   "description": "PPS on the ng band calculated in 30 second buckets.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name:$col",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" }
     ]
    }
   ]
  },
  {
   "title": "5GHz Drops/Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name:$col",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "radio" ], "type": "tag" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "rx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Drop:In" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Drop:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Error:In" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Error:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_crypts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "BadCrypt:In" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_frags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "BadFrag:In" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_retries" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "ExsRetry:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" }
     ]
    }
   ]
  },
  {
   "title": "2.4GHz Drops/Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name:$col",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "rx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Drop:In" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Drop:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Error:In" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Error:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_crypts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "BadCrypt:In" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_frags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "BadFrag:In" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_retries" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "ExsRetry:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" }
     ]
    }
   ]
  }
 ]
}