{
 "title": "Unifi Client Insights",
 "time": { "from": "now-3h", "to": "now-20s" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Site",
    "query": "show tag values from \"clients\" with key=\"site_name\""
   },
   {
    "name": "AP",
    "query": "show tag values from \"clients\" with key=\"ap_mac\" where  site_name =~ /$Site$/"
   },
   {
    "name": "Client",
    "query": "show tag values from \"clients\" with key=\"name\" where  site_name =~ /$Site$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Wireless Devices",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "oui" ], "type": "tag" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "radio" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "ap_mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT last(\"ip\") AS \"Address\", last(\"note\") AS \"Note\", last(\"network\") AS \"Network\" FROM \"clients\" WHERE (\"is_wired\" = 'false' AND \"ap_mac\" =~ /^$AP$/) AND $timeFilter GROUP BY \"mac\", \"oui\", \"channel\", \"radio\", \"name\", \"ap_mac\"",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Address" ], "type": "alias" }
      ],
      [
       { "params": [ "note" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Note" ], "type": "alias" }
      ],
      [
       { "params": [ "network" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Network" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "ap_mac", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Wired Devices",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sw_port" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "oui" ], "type": "tag" },
      { "params": [ "use_fixedip" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT last(\"ip\") AS \"Address\", last(\"note\") AS \"Note\", last(\"network\") AS \"Network\" FROM \"clients\" WHERE (\"is_wired\" != 'false' AND \"name\" =~ /^$Client$/ AND \"site_name\" =~ /$Site$/) AND $timeFilter GROUP BY \"sw_port\", \"mac\", \"oui\", \"use_fixedip\", \"name\"",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Address" ], "type": "alias" }
      ],
      [
       { "params": [ "note" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Note" ], "type": "alias" }
      ],
      [
       { "params": [ "network" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Network" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "true" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" }
     ]
    }
   ]
  },
  {
   "title": "Wifi Channels",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Wired",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE time > now() - 10m AND is_wired = 'true' AND \"site_name\" =~ /$Site$/ group by hostname",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "Channel $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE time > now() - 10m AND (is_wired != 'true' AND \"site_name\" =~ /$Site$/ AND \"ap_mac\" =~ /^$AP$/ AND \"name\" =~ /^$Client$/) group by channel",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AP Radio / Clients",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_ap_mac / $tag_radio_proto / $tag_radio / $tag_radio_name",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE (time > now() - 10m AND ap_mac =~ /$AP$/ AND \"site_name\" =~ /$Site$/ and  \"name\" =~ /^$Client$/) group by radio_proto, radio, radio_name, ap_mac",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Client MAC OUI Breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "w $tag_oui",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE (time > now() - 60m AND \"name\" =~ /^$Client$/ AND \"ap_mac\" =~ /^$AP$/ and site_name =~ /$Site$/ and \"name\" =~ /^$Client$/) group by oui",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "e $tag_oui",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE (time > now() - 60m  AND \"is_wired\" = 'true' and site_name =~ /$Site$/) group by oui",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "OS/Dev Class/ID Breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_os_class, $tag_os_name, $tag_dev_cat, $tag_dev_family, $tag_dev_id,",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE (time > now() - 10m AND \"ap_mac\" =~ /^$AP$/ AND \"name\" =~ /^$Client$/ AND \"site_name\" =~ /$Site$/) group by os_class, os_name, dev_cat, dev_family, dev_id ",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "UAP Bandwidth / Wireless Devices",
   "type": "graph",
   "description": "Bandwidth usage per wireless devices as reported by the UAPs. Does not include amazon devices.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "name", "operator": "!~", "value": "/^(amazon-)/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
      { "condition": "AND", "key": "ap_mac", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Switch Bandwidth / Cameras",
   "type": "graph",
   "description": "Cameras TX / RX bytes per second (calculated in 1 minute buckets).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "wired-rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "wired-tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^camera/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Switch Bandwidth / Echos & FireTVs",
   "type": "graph",
   "description": "Amazon Devices TX / RX bytes per second (calculated in 30 second buckets).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "w $tag_name $col",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "wired-rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "wired-tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^amazon-(.*)/" },
      { "condition": "AND", "key": "is_wired", "operator": "!=", "value": "true" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
      { "condition": "AND", "key": "ap_mac", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    },
    {
     "alias": "e $tag_name $col",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^amazon-(.*)/" },
      { "condition": "AND", "key": "is_wired", "operator": "!=", "value": "false" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Switch Bandwidth / Wired Devices",
   "type": "graph",
   "description": "Wired TX / RX bytes per second (calculated in 30 second buckets). Does not include amazon and camera devices. Unaffected by the AP setting.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "wired-rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "wired-tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "true" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "!~",
       "value": "/^(supermic-bmc|amazon-|camera-)/"
      },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Wifi Client / AP",
   "type": "natel-discrete-panel",
   "description": "Shows which wireless radio a client is connected to. Setting AP does not change this.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "clients",
     "select": [
      [
       { "params": [ "bssid" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "!=", "value": "true" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
      { "condition": "AND", "key": "ap_mac", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Client / IP",
   "type": "natel-discrete-panel",
   "description": "Shows IPs assigned to non-static clients.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "clients",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "use_fixedip", "operator": "!=", "value": "true" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
      { "condition": "AND", "key": "ap_mac", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Received Signal Strength Indicator",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "RSSI Quality" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
      { "condition": "AND", "key": "ap_mac", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Wireless Signal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "dBm", "label": "Signal Power" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "signal" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
      { "condition": "AND", "key": "ap_mac", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "UAP Client Stats / Noise",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short", "label": "Noise" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "noise" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
      { "condition": "AND", "key": "ap_mac", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "tx_power" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "!=", "value": "true" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Client$/" },
      { "condition": "AND", "key": "ap_mac", "operator": "=~", "value": "/^$AP$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  }
 ]
}