{
 "title": "UniFi UAP Insights",
 "tags": [
  "unifi",
  "uap"
 ],
 "time": { "from": "now-3h", "to": "now-5s" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "dataSource", "query": "influxdb" },
   {
    "name": "Site",
    "query": "show tag values from \"uap\" with key=\"site_name\""
   },
   {
    "name": "host",
    "label": "UniFi AP:",
    "query": "show tag values from \"uap\" with key=\"name\"  where site_name =~ /$Site$/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "content": "<br>\n<center><b><font size=\"6px\">Unifi UAP</font></b></center>\n"
  },
  {
   "title": "Clients per Band - All APs",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_radio_proto",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE ($timeFilter and  is_wired != 'true' and site_name =~ /$Site$/) group by radio_proto",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Client per Wifi Channels - All APs",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Chan $tag_channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE $timeFilter AND is_wired != 'true' and site_name =~ /$Site$/ group by channel",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Client MAC OUI Breakdown - All APs",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_oui",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE $timeFilter AND \"is_wired\" != 'true' and site_name =~ /$Site$/ group by oui",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Total Users - All APs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "query": "select count(distinct(hostname)) FROM \"clients\" WHERE ($timeFilter and  is_wired != 'true' and site_name =~ /$Site$/)",
     "select": [
      [
       { "params": [ "channel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "$host 2.4GHz Channel",
   "type": "singlestat",
   "description": "This only works when 1 AP is selected.",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "channel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  { "title": "Now", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 } },
  {
   "title": "5GHz Radio Channel",
   "type": "singlestat",
   "description": "This only works when 1 AP is selected.",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "query": "SELECT \"channel\" FROM \"uap_radios\" WHERE (\"device_name\" =~ /^$host$/ AND \"radio\" = 'na') AND $timeFilter GROUP BY \"device_name\"",
     "select": [
      [
       { "params": [ "channel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "AP Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "model" ], "type": "tag" },
      { "params": [ "cfgversion" ], "type": "tag" },
      { "params": [ "board_rev" ], "type": "tag" },
      { "params": [ "serial" ], "type": "tag" },
      { "params": [ "site_id" ], "type": "tag" },
      { "params": [ "bandsteering_mode" ], "type": "tag" },
      { "params": [ "device_ap" ], "type": "tag" },
      { "params": [ "guest-num_sta" ], "type": "tag" }
     ],
     "measurement": "uap",
     "select": [
      [
       { "params": [ "version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Version" ], "type": "alias" }
      ],
      [
       { "params": [ "ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "IP" ], "type": "alias" }
      ],
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "last_seen" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" },
       { "params": [ "Last Seen" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CPU" ], "type": "alias" }
      ],
      [
       { "params": [ "user-num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Users" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "uap",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "uap",
     "query": "SELECT \"mem_used\" FROM \"uap\" WHERE (\"name\" =~ /^$host$/ AND \"site_name\" =~ /^$Site$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "mem" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "uap",
     "select": [
      [
       { "params": [ "loadavg_1" ], "type": "field" },
       { "params": [ "load 1" ], "type": "alias" }
      ],
      [
       { "params": [ "loadavg_5" ], "type": "field" },
       { "params": [ "laid 5" ], "type": "alias" }
      ],
      [
       { "params": [ "loadavg_15" ], "type": "field" },
       { "params": [ "load15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Clients per Access Point",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "query": "SELECT last(\"num_sta\") FROM \"uap_radios\" WHERE (\"device_name\" =~ /^$host$/ AND \"radio\" = 'na') AND $timeFilter GROUP BY time($__interval), \"device_name\"",
     "select": [
      [
       { "params": [ "num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "site_name", "operator": "=~", "value": "/^$Site$/" },
      { "condition": "AND", "key": "device_name", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "WIFI Traffic per Vendor (all AP in Site(s): $Site)",
   "type": "graph",
   "description": "Devices TX / RX bytes per second grouped by OUI. RX on negative axis.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_oui $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "oui" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(sum(\"rx_bytes\"), 1s) AS \"Rx\", derivative(sum(\"rx_bytes\"), 1s) AS \"Rx\" FROM \"clients\" WHERE (\"oui\" = 'Htc' AND \"is_wired\" = 'false') AND $timeFilter GROUP BY time(30s), \"oui\" fill(none)",
     "select": [
      [
       { "params": [ "tx_bytes_r" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "rx_bytes_r" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "!=", "value": "true" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Users and Guests per AP band",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name 5GHz $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "user-num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Users" ], "type": "alias" }
      ],
      [
       { "params": [ "guest-num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Guests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    },
    {
     "alias": "$tag_device_name 2.4GHz $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "guest-num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Guests" ], "type": "alias" }
      ],
      [
       { "params": [ "user-num_sta" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Users" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Client Connection Quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "ccq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "Rssi (all APs in Site(s): $Site)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "dBm", "label": "Rssi" }
   ],
   "targets": [
    {
     "alias": "$tag_ap_mac",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ap_mac" ], "type": "tag" }
     ],
     "measurement": "clients",
     "query": "SELECT derivative(first(\"wired-rx_bytes\"), 1s) FROM \"clients\" WHERE (\"hostname\" = 'dns-rtn') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "is_wired", "operator": "!=", "value": "true" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "5 GHz Channel Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "cu_self_rx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "cu_self_tx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "cu_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "2.4GHz Channel Utilization",
   "type": "graph",
   "description": "Displays 2.4GHz usage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "cu_self_rx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "cu_self_tx" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tx" ], "type": "alias" }
      ],
      [
       { "params": [ "cu_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "5 GHz Traffic",
   "type": "graph",
   "description": "RX is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "vap_rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "2.4GHz Traffic",
   "type": "graph",
   "description": "RX is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "vap_rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "5 GHz Packets",
   "type": "graph",
   "description": "PPS on the na band. In is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "vap_rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_tx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "2.4GHz Packets",
   "type": "graph",
   "description": "PPS on the ng band calculated in 30 second buckets. In is on the negative Axis.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "vap_rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_tx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "5GHz Drops/Errors",
   "type": "graph",
   "description": "Visualize packet errors (several types)  per second in the 5GHz band.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "radio" ], "type": "tag" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "vap_rx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Drop:In" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_tx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Drop:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_rx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Error:In" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_tx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Error:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_rx_crypts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "BadCrypt:In" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_rx_frags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "BadFrag:In" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_tx_retries" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "ExsRetry:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "na" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  },
  {
   "title": "2.4GHz Drops/Errors",
   "type": "graph",
   "description": "In is on the negative axis.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_device_name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uap_radios",
     "select": [
      [
       { "params": [ "vap_rx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Drop:In" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_tx_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Drop:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_rx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Error:In" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_tx_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "Error:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_rx_crypts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "BadCrypt:In" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_rx_frags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "BadFrag:In" ], "type": "alias" }
      ],
      [
       { "params": [ "vap_tx_retries" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "ExsRetry:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "radio", "operator": "=", "value": "ng" },
      { "condition": "AND", "key": "site_name", "operator": "=~", "value": "/^$Site$/" }
     ]
    }
   ]
  }
 ]
}