package unifi

// USW represents all the data from the Ubiquiti Controller for a Unifi Switch.
type USW struct {
	ID            string   `json:"_id"`
	UUptime       float64  `json:"_uptime"`
	AdoptIP       string   `json:"adopt_ip"`
	AdoptURL      string   `json:"adopt_url"`
	Adopted       FlexBool `json:"adopted"`
	BoardRev      float64  `json:"board_rev"`
	Bytes         float64  `json:"bytes"`
	Cfgversion    string   `json:"cfgversion"`
	ConfigNetwork struct {
		IP   string `json:"ip"`
		Type string `json:"type"`
	} `json:"config_network"`
	ConnectRequestIP     string        `json:"connect_request_ip"`
	ConnectRequestPort   string        `json:"connect_request_port"`
	ConsideredLostAt     float64       `json:"considered_lost_at"`
	Default              FlexBool      `json:"default"`
	DeviceID             string        `json:"device_id"`
	DhcpServerTable      []interface{} `json:"dhcp_server_table"`
	DiscoveredVia        string        `json:"discovered_via"`
	Dot1XPortctrlEnabled FlexBool      `json:"dot1x_portctrl_enabled"`
	DownlinkTable        []struct {
		FullDuplex FlexBool `json:"full_duplex"`
		Mac        string   `json:"mac"`
		PortIdx    float64  `json:"port_idx"`
		Speed      float64  `json:"speed"`
	} `json:"downlink_table"`
	EthernetTable []struct {
		Mac     string  `json:"mac"`
		Name    string  `json:"name"`
		NumPort float64 `json:"num_port,omitempty"`
	} `json:"ethernet_table"`
	FanLevel           float64  `json:"fan_level"`
	FlowctrlEnabled    FlexBool `json:"flowctrl_enabled"`
	FwCaps             float64  `json:"fw_caps"`
	GeneralTemperature float64  `json:"general_temperature"`
	GuestNumSta        float64  `json:"guest-num_sta"`
	HasFan             FlexBool `json:"has_fan"`
	HasTemperature     FlexBool `json:"has_temperature"`
	InformIP           string   `json:"inform_ip"`
	InformURL          string   `json:"inform_url"`
	IP                 string   `json:"ip"`
	JumboframeEnabled  FlexBool `json:"jumboframe_enabled"`
	KnownCfgversion    string   `json:"known_cfgversion"`
	LastSeen           float64  `json:"last_seen"`
	LastUplink         struct {
		UplinkMac string `json:"uplink_mac"`
	} `json:"last_uplink"`
	LedOverride         string   `json:"led_override"`
	LicenseState        string   `json:"license_state"`
	Locating            FlexBool `json:"locating"`
	Mac                 string   `json:"mac"`
	Model               string   `json:"model"`
	Name                string   `json:"name"`
	NextHeartbeatAt     float64  `json:"next_heartbeat_at"`
	NumSta              float64  `json:"num_sta"`
	OutdoorModeOverride string   `json:"outdoor_mode_override"`
	Overheating         FlexBool `json:"overheating"`
	PortOverrides       []struct {
		Name       string  `json:"name,omitempty"`
		PoeMode    string  `json:"poe_mode,omitempty"`
		PortIdx    float64 `json:"port_idx"`
		PortconfID string  `json:"portconf_id"`
	} `json:"port_overrides"`
	PortTable []struct {
		AggregatedBy FlexBool      `json:"aggregated_by"`
		Autoneg      FlexBool      `json:"autoneg"`
		BytesR       float64       `json:"bytes-r"`
		Dot1XMode    string        `json:"dot1x_mode"`
		Dot1XStatus  string        `json:"dot1x_status"`
		Enable       FlexBool      `json:"enable"`
		FlowctrlRx   FlexBool      `json:"flowctrl_rx"`
		FlowctrlTx   FlexBool      `json:"flowctrl_tx"`
		FullDuplex   FlexBool      `json:"full_duplex"`
		IsUplink     FlexBool      `json:"is_uplink"`
		Jumbo        FlexBool      `json:"jumbo"`
		LldpTable    []interface{} `json:"lldp_table"`
		Masked       FlexBool      `json:"masked"`
		Media        string        `json:"media"`
		Name         string        `json:"name"`
		OpMode       string        `json:"op_mode"`
		PoeCaps      float64       `json:"poe_caps"`
		PoeClass     string        `json:"poe_class,omitempty"`
		PoeCurrent   string        `json:"poe_current,omitempty"`
		PoeEnable    FlexBool      `json:"poe_enable,omitempty"`
		PoeGood      FlexBool      `json:"poe_good,omitempty"`
		PoeMode      string        `json:"poe_mode,omitempty"`
		PoePower     string        `json:"poe_power,omitempty"`
		PoeVoltage   string        `json:"poe_voltage,omitempty"`
		PortIdx      float64       `json:"port_idx"`
		PortPoe      FlexBool      `json:"port_poe"`
		PortconfID   string        `json:"portconf_id"`
		RxBroadcast  float64       `json:"rx_broadcast"`
		RxBytes      float64       `json:"rx_bytes"`
		RxBytesR     float64       `json:"rx_bytes-r"`
		RxDropped    float64       `json:"rx_dropped"`
		RxErrors     float64       `json:"rx_errors"`
		RxMulticast  float64       `json:"rx_multicast"`
		RxPackets    float64       `json:"rx_packets"`
		Speed        float64       `json:"speed"`
		StpPathcost  float64       `json:"stp_pathcost"`
		StpState     string        `json:"stp_state"`
		TxBroadcast  float64       `json:"tx_broadcast"`
		TxBytes      float64       `json:"tx_bytes"`
		TxBytesR     float64       `json:"tx_bytes-r"`
		TxDropped    float64       `json:"tx_dropped"`
		TxErrors     float64       `json:"tx_errors"`
		TxMulticast  float64       `json:"tx_multicast"`
		TxPackets    float64       `json:"tx_packets"`
		Up           FlexBool      `json:"up"`
		SfpFound     FlexBool      `json:"sfp_found,omitempty"`
	} `json:"port_table"`
	Rollupgrade     FlexBool      `json:"rollupgrade"`
	RxBytes         float64       `json:"rx_bytes"`
	Serial          string        `json:"serial"`
	SiteID          string        `json:"site_id"`
	SiteName        string        `json:"-"`
	SSHSessionTable []interface{} `json:"ssh_session_table"`

	Stat struct {
		Bytes             float64 `json:"bytes"`
		Datetime          string  `json:"datetime"`
		Duration          float64 `json:"duration"`
		O                 string  `json:"o"`
		Oid               string  `json:"oid"`
		Port1RxBroadcast  float64 `json:"port_1-rx_broadcast"`
		Port1RxBytes      float64 `json:"port_1-rx_bytes"`
		Port1RxDropped    float64 `json:"port_1-rx_dropped"`
		Port1RxMulticast  float64 `json:"port_1-rx_multicast"`
		Port1RxPackets    float64 `json:"port_1-rx_packets"`
		Port1TxBroadcast  float64 `json:"port_1-tx_broadcast"`
		Port1TxBytes      float64 `json:"port_1-tx_bytes"`
		Port1TxMulticast  float64 `json:"port_1-tx_multicast"`
		Port1TxPackets    float64 `json:"port_1-tx_packets"`
		Port2RxBroadcast  float64 `json:"port_2-rx_broadcast"`
		Port2RxBytes      float64 `json:"port_2-rx_bytes"`
		Port2RxDropped    float64 `json:"port_2-rx_dropped"`
		Port2RxMulticast  float64 `json:"port_2-rx_multicast"`
		Port2RxPackets    float64 `json:"port_2-rx_packets"`
		Port2TxBroadcast  float64 `json:"port_2-tx_broadcast"`
		Port2TxBytes      float64 `json:"port_2-tx_bytes"`
		Port2TxMulticast  float64 `json:"port_2-tx_multicast"`
		Port2TxPackets    float64 `json:"port_2-tx_packets"`
		Port3RxBroadcast  float64 `json:"port_3-rx_broadcast"`
		Port3RxBytes      float64 `json:"port_3-rx_bytes"`
		Port3RxDropped    float64 `json:"port_3-rx_dropped"`
		Port3RxMulticast  float64 `json:"port_3-rx_multicast"`
		Port3RxPackets    float64 `json:"port_3-rx_packets"`
		Port3TxBroadcast  float64 `json:"port_3-tx_broadcast"`
		Port3TxBytes      float64 `json:"port_3-tx_bytes"`
		Port3TxMulticast  float64 `json:"port_3-tx_multicast"`
		Port3TxPackets    float64 `json:"port_3-tx_packets"`
		Port4RxBroadcast  float64 `json:"port_4-rx_broadcast"`
		Port4RxBytes      float64 `json:"port_4-rx_bytes"`
		Port4RxDropped    float64 `json:"port_4-rx_dropped"`
		Port4RxMulticast  float64 `json:"port_4-rx_multicast"`
		Port4RxPackets    float64 `json:"port_4-rx_packets"`
		Port4TxBroadcast  float64 `json:"port_4-tx_broadcast"`
		Port4TxBytes      float64 `json:"port_4-tx_bytes"`
		Port4TxMulticast  float64 `json:"port_4-tx_multicast"`
		Port4TxPackets    float64 `json:"port_4-tx_packets"`
		Port5RxBroadcast  float64 `json:"port_5-rx_broadcast"`
		Port5RxBytes      float64 `json:"port_5-rx_bytes"`
		Port5RxDropped    float64 `json:"port_5-rx_dropped"`
		Port5RxMulticast  float64 `json:"port_5-rx_multicast"`
		Port5RxPackets    float64 `json:"port_5-rx_packets"`
		Port5TxBroadcast  float64 `json:"port_5-tx_broadcast"`
		Port5TxBytes      float64 `json:"port_5-tx_bytes"`
		Port5TxMulticast  float64 `json:"port_5-tx_multicast"`
		Port5TxPackets    float64 `json:"port_5-tx_packets"`
		Port6RxBroadcast  float64 `json:"port_6-rx_broadcast"`
		Port6RxBytes      float64 `json:"port_6-rx_bytes"`
		Port6RxDropped    float64 `json:"port_6-rx_dropped"`
		Port6RxMulticast  float64 `json:"port_6-rx_multicast"`
		Port6RxPackets    float64 `json:"port_6-rx_packets"`
		Port6TxBroadcast  float64 `json:"port_6-tx_broadcast"`
		Port6TxBytes      float64 `json:"port_6-tx_bytes"`
		Port6TxMulticast  float64 `json:"port_6-tx_multicast"`
		Port6TxPackets    float64 `json:"port_6-tx_packets"`
		Port7RxBroadcast  float64 `json:"port_7-rx_broadcast"`
		Port7RxBytes      float64 `json:"port_7-rx_bytes"`
		Port7RxDropped    float64 `json:"port_7-rx_dropped"`
		Port7RxMulticast  float64 `json:"port_7-rx_multicast"`
		Port7RxPackets    float64 `json:"port_7-rx_packets"`
		Port7TxBroadcast  float64 `json:"port_7-tx_broadcast"`
		Port7TxBytes      float64 `json:"port_7-tx_bytes"`
		Port7TxMulticast  float64 `json:"port_7-tx_multicast"`
		Port7TxPackets    float64 `json:"port_7-tx_packets"`
		Port8RxBroadcast  float64 `json:"port_8-rx_broadcast"`
		Port8RxBytes      float64 `json:"port_8-rx_bytes"`
		Port8RxDropped    float64 `json:"port_8-rx_dropped"`
		Port8RxMulticast  float64 `json:"port_8-rx_multicast"`
		Port8RxPackets    float64 `json:"port_8-rx_packets"`
		Port8TxBroadcast  float64 `json:"port_8-tx_broadcast"`
		Port8TxBytes      float64 `json:"port_8-tx_bytes"`
		Port8TxMulticast  float64 `json:"port_8-tx_multicast"`
		Port8TxPackets    float64 `json:"port_8-tx_packets"`
		Port9RxBroadcast  float64 `json:"port_9-rx_broadcast"`
		Port9RxBytes      float64 `json:"port_9-rx_bytes"`
		Port9RxDropped    float64 `json:"port_9-rx_dropped"`
		Port9RxMulticast  float64 `json:"port_9-rx_multicast"`
		Port9RxPackets    float64 `json:"port_9-rx_packets"`
		Port9TxBroadcast  float64 `json:"port_9-tx_broadcast"`
		Port9TxBytes      float64 `json:"port_9-tx_bytes"`
		Port9TxMulticast  float64 `json:"port_9-tx_multicast"`
		Port9TxPackets    float64 `json:"port_9-tx_packets"`
		Port10RxBroadcast float64 `json:"port_10-rx_broadcast"`
		Port10RxBytes     float64 `json:"port_10-rx_bytes"`
		Port10RxDropped   float64 `json:"port_10-rx_dropped"`
		Port10RxMulticast float64 `json:"port_10-rx_multicast"`
		Port10RxPackets   float64 `json:"port_10-rx_packets"`
		Port10TxBroadcast float64 `json:"port_10-tx_broadcast"`
		Port10TxBytes     float64 `json:"port_10-tx_bytes"`
		Port10TxMulticast float64 `json:"port_10-tx_multicast"`
		Port10TxPackets   float64 `json:"port_10-tx_packets"`
		Port11RxBroadcast float64 `json:"port_11-rx_broadcast"`
		Port11RxBytes     float64 `json:"port_11-rx_bytes"`
		Port11RxDropped   float64 `json:"port_11-rx_dropped"`
		Port11RxMulticast float64 `json:"port_11-rx_multicast"`
		Port11RxPackets   float64 `json:"port_11-rx_packets"`
		Port11TxBroadcast float64 `json:"port_11-tx_broadcast"`
		Port11TxBytes     float64 `json:"port_11-tx_bytes"`
		Port11TxMulticast float64 `json:"port_11-tx_multicast"`
		Port11TxPackets   float64 `json:"port_11-tx_packets"`
		Port12RxBroadcast float64 `json:"port_12-rx_broadcast"`
		Port12RxBytes     float64 `json:"port_12-rx_bytes"`
		Port12RxDropped   float64 `json:"port_12-rx_dropped"`
		Port12RxMulticast float64 `json:"port_12-rx_multicast"`
		Port12RxPackets   float64 `json:"port_12-rx_packets"`
		Port12TxBroadcast float64 `json:"port_12-tx_broadcast"`
		Port12TxBytes     float64 `json:"port_12-tx_bytes"`
		Port12TxMulticast float64 `json:"port_12-tx_multicast"`
		Port12TxPackets   float64 `json:"port_12-tx_packets"`
		Port13RxBroadcast float64 `json:"port_13-rx_broadcast"`
		Port13RxBytes     float64 `json:"port_13-rx_bytes"`
		Port13RxDropped   float64 `json:"port_13-rx_dropped"`
		Port13RxMulticast float64 `json:"port_13-rx_multicast"`
		Port13RxPackets   float64 `json:"port_13-rx_packets"`
		Port13TxBroadcast float64 `json:"port_13-tx_broadcast"`
		Port13TxBytes     float64 `json:"port_13-tx_bytes"`
		Port13TxMulticast float64 `json:"port_13-tx_multicast"`
		Port13TxPackets   float64 `json:"port_13-tx_packets"`
		Port14RxBroadcast float64 `json:"port_14-rx_broadcast"`
		Port14RxBytes     float64 `json:"port_14-rx_bytes"`
		Port14RxDropped   float64 `json:"port_14-rx_dropped"`
		Port14RxMulticast float64 `json:"port_14-rx_multicast"`
		Port14RxPackets   float64 `json:"port_14-rx_packets"`
		Port14TxBroadcast float64 `json:"port_14-tx_broadcast"`
		Port14TxBytes     float64 `json:"port_14-tx_bytes"`
		Port14TxMulticast float64 `json:"port_14-tx_multicast"`
		Port14TxPackets   float64 `json:"port_14-tx_packets"`
		Port15RxBroadcast float64 `json:"port_15-rx_broadcast"`
		Port15RxBytes     float64 `json:"port_15-rx_bytes"`
		Port15RxDropped   float64 `json:"port_15-rx_dropped"`
		Port15RxMulticast float64 `json:"port_15-rx_multicast"`
		Port15RxPackets   float64 `json:"port_15-rx_packets"`
		Port15TxBroadcast float64 `json:"port_15-tx_broadcast"`
		Port15TxBytes     float64 `json:"port_15-tx_bytes"`
		Port15TxMulticast float64 `json:"port_15-tx_multicast"`
		Port15TxPackets   float64 `json:"port_15-tx_packets"`
		Port16RxBroadcast float64 `json:"port_16-rx_broadcast"`
		Port16RxBytes     float64 `json:"port_16-rx_bytes"`
		Port16RxDropped   float64 `json:"port_16-rx_dropped"`
		Port16RxMulticast float64 `json:"port_16-rx_multicast"`
		Port16RxPackets   float64 `json:"port_16-rx_packets"`
		Port16TxBroadcast float64 `json:"port_16-tx_broadcast"`
		Port16TxBytes     float64 `json:"port_16-tx_bytes"`
		Port16TxMulticast float64 `json:"port_16-tx_multicast"`
		Port16TxPackets   float64 `json:"port_16-tx_packets"`
		Port17RxBroadcast float64 `json:"port_17-rx_broadcast"`
		Port17RxBytes     float64 `json:"port_17-rx_bytes"`
		Port17RxDropped   float64 `json:"port_17-rx_dropped"`
		Port17RxMulticast float64 `json:"port_17-rx_multicast"`
		Port17RxPackets   float64 `json:"port_17-rx_packets"`
		Port17TxBroadcast float64 `json:"port_17-tx_broadcast"`
		Port17TxBytes     float64 `json:"port_17-tx_bytes"`
		Port17TxMulticast float64 `json:"port_17-tx_multicast"`
		Port17TxPackets   float64 `json:"port_17-tx_packets"`
		Port18RxBroadcast float64 `json:"port_18-rx_broadcast"`
		Port18RxBytes     float64 `json:"port_18-rx_bytes"`
		Port18RxDropped   float64 `json:"port_18-rx_dropped"`
		Port18RxMulticast float64 `json:"port_18-rx_multicast"`
		Port18RxPackets   float64 `json:"port_18-rx_packets"`
		Port18TxBroadcast float64 `json:"port_18-tx_broadcast"`
		Port18TxBytes     float64 `json:"port_18-tx_bytes"`
		Port18TxMulticast float64 `json:"port_18-tx_multicast"`
		Port18TxPackets   float64 `json:"port_18-tx_packets"`
		Port19RxBroadcast float64 `json:"port_19-rx_broadcast"`
		Port19RxBytes     float64 `json:"port_19-rx_bytes"`
		Port19RxDropped   float64 `json:"port_19-rx_dropped"`
		Port19RxMulticast float64 `json:"port_19-rx_multicast"`
		Port19RxPackets   float64 `json:"port_19-rx_packets"`
		Port19TxBroadcast float64 `json:"port_19-tx_broadcast"`
		Port19TxBytes     float64 `json:"port_19-tx_bytes"`
		Port19TxMulticast float64 `json:"port_19-tx_multicast"`
		Port19TxPackets   float64 `json:"port_19-tx_packets"`
		Port20RxBroadcast float64 `json:"port_20-rx_broadcast"`
		Port20RxBytes     float64 `json:"port_20-rx_bytes"`
		Port20RxDropped   float64 `json:"port_20-rx_dropped"`
		Port20RxMulticast float64 `json:"port_20-rx_multicast"`
		Port20RxPackets   float64 `json:"port_20-rx_packets"`
		Port20TxBroadcast float64 `json:"port_20-tx_broadcast"`
		Port20TxBytes     float64 `json:"port_20-tx_bytes"`
		Port20TxMulticast float64 `json:"port_20-tx_multicast"`
		Port20TxPackets   float64 `json:"port_20-tx_packets"`
		Port21RxBroadcast float64 `json:"port_21-rx_broadcast"`
		Port21RxBytes     float64 `json:"port_21-rx_bytes"`
		Port21RxDropped   float64 `json:"port_21-rx_dropped"`
		Port21RxMulticast float64 `json:"port_21-rx_multicast"`
		Port21RxPackets   float64 `json:"port_21-rx_packets"`
		Port21TxBroadcast float64 `json:"port_21-tx_broadcast"`
		Port21TxBytes     float64 `json:"port_21-tx_bytes"`
		Port21TxMulticast float64 `json:"port_21-tx_multicast"`
		Port21TxPackets   float64 `json:"port_21-tx_packets"`
		Port22RxBroadcast float64 `json:"port_22-rx_broadcast"`
		Port22RxBytes     float64 `json:"port_22-rx_bytes"`
		Port22RxDropped   float64 `json:"port_22-rx_dropped"`
		Port22RxMulticast float64 `json:"port_22-rx_multicast"`
		Port22RxPackets   float64 `json:"port_22-rx_packets"`
		Port22TxBroadcast float64 `json:"port_22-tx_broadcast"`
		Port22TxBytes     float64 `json:"port_22-tx_bytes"`
		Port22TxMulticast float64 `json:"port_22-tx_multicast"`
		Port22TxPackets   float64 `json:"port_22-tx_packets"`
		Port23RxBroadcast float64 `json:"port_23-rx_broadcast"`
		Port23RxBytes     float64 `json:"port_23-rx_bytes"`
		Port23RxDropped   float64 `json:"port_23-rx_dropped"`
		Port23RxMulticast float64 `json:"port_23-rx_multicast"`
		Port23RxPackets   float64 `json:"port_23-rx_packets"`
		Port23TxBroadcast float64 `json:"port_23-tx_broadcast"`
		Port23TxBytes     float64 `json:"port_23-tx_bytes"`
		Port23TxMulticast float64 `json:"port_23-tx_multicast"`
		Port23TxPackets   float64 `json:"port_23-tx_packets"`
		Port24RxBroadcast float64 `json:"port_24-rx_broadcast"`
		Port24RxBytes     float64 `json:"port_24-rx_bytes"`
		Port24RxDropped   float64 `json:"port_24-rx_dropped"`
		Port24RxMulticast float64 `json:"port_24-rx_multicast"`
		Port24RxPackets   float64 `json:"port_24-rx_packets"`
		Port24TxBroadcast float64 `json:"port_24-tx_broadcast"`
		Port24TxBytes     float64 `json:"port_24-tx_bytes"`
		Port24TxMulticast float64 `json:"port_24-tx_multicast"`
		Port24TxPackets   float64 `json:"port_24-tx_packets"`
		// Have a 48 port switch? How 'bout a pull request. :D
		RxBroadcast float64 `json:"rx_broadcast"`
		RxBytes     float64 `json:"rx_bytes"`
		RxCrypts    float64 `json:"rx_crypts"`
		RxDropped   float64 `json:"rx_dropped"`
		RxErrors    float64 `json:"rx_errors"`
		RxFrags     float64 `json:"rx_frags"`
		RxMulticast float64 `json:"rx_multicast"`
		RxPackets   float64 `json:"rx_packets"`
		SiteID      string  `json:"site_id"`
		Sw          string  `json:"sw"`
		Time        float64 `json:"time"`
		TxBroadcast float64 `json:"tx_broadcast"`
		TxBytes     float64 `json:"tx_bytes"`
		TxDropped   float64 `json:"tx_dropped"`
		TxErrors    float64 `json:"tx_errors"`
		TxMulticast float64 `json:"tx_multicast"`
		TxPackets   float64 `json:"tx_packets"`
		TxRetries   float64 `json:"tx_retries"`
	} `json:"stat"`

	State       float64 `json:"state"`
	StpPriority string  `json:"stp_priority"`
	StpVersion  string  `json:"stp_version"`
	SysStats    struct {
		Loadavg1  float64 `json:"loadavg_1,string"`
		Loadavg15 float64 `json:"loadavg_15,string"`
		Loadavg5  float64 `json:"loadavg_5,string"`
		MemBuffer float64 `json:"mem_buffer"`
		MemTotal  float64 `json:"mem_total"`
		MemUsed   float64 `json:"mem_used"`
	} `json:"sys_stats"`
	SystemStats struct {
		CPU    float64 `json:"cpu,string"`
		Mem    float64 `json:"mem,string"`
		Uptime float64 `json:"uptime,string"`
	} `json:"system-stats"`
	TxBytes    float64  `json:"tx_bytes"`
	Type       string   `json:"type"`
	Upgradable FlexBool `json:"upgradable"`
	Uplink     struct {
		FullDuplex  FlexBool `json:"full_duplex"`
		IP          string   `json:"ip"`
		Mac         string   `json:"mac"`
		MaxSpeed    float64  `json:"max_speed"`
		Media       string   `json:"media"`
		Name        string   `json:"name"`
		Netmask     string   `json:"netmask"`
		NumPort     float64  `json:"num_port"`
		PortIdx     float64  `json:"port_idx"`
		RxBytes     float64  `json:"rx_bytes"`
		RxBytesR    float64  `json:"rx_bytes-r"`
		RxDropped   float64  `json:"rx_dropped"`
		RxErrors    float64  `json:"rx_errors"`
		RxMulticast float64  `json:"rx_multicast"`
		RxPackets   float64  `json:"rx_packets"`
		Speed       float64  `json:"speed"`
		TxBytes     float64  `json:"tx_bytes"`
		TxBytesR    float64  `json:"tx_bytes-r"`
		TxDropped   float64  `json:"tx_dropped"`
		TxErrors    float64  `json:"tx_errors"`
		TxPackets   float64  `json:"tx_packets"`
		Type        string   `json:"type"`
		Up          FlexBool `json:"up"`
		UplinkMac   string   `json:"uplink_mac"`
	} `json:"uplink"`
	UplinkDepth         FlexInt  `json:"uplink_depth"`
	Uptime              float64  `json:"uptime"`
	UserNumSta          float64  `json:"user-num_sta"`
	Version             string   `json:"version"`
	VersionIncompatible FlexBool `json:"version_incompatible"`
}
